[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd apps/backend",
  "pnpm build-production"
]

[start]
cmd = "cd apps/backend && pnpm start:prod"
